Update README.md
mobadarah/tajmeeaton pull request #19
Opened 2024-04-18 12:57 UTC by Adrhman

جبر برنامج حل مسائل رياضيات قادر على حل المسائل وعرضها بالصيغ والأرقام العربية https://play.google.com/store/apps/details?id=com.kahraba4u.jabr
![ic_launcher-playstore](https://github.com/mobadarah/tajmeeaton/assets/79088239/030dd6cd-842e-4f1f-a567-0c2e3419a22e)

2024-04-24 07:36 UTC, MuhammadSawalhy requested changes

2024-04-24 07:36 UTC, MuhammadSawalhy commented on README.md
> +   <span dir=rtl>جبرأول برنامج أندرويد يمكنه حل مسائل رياضيات وعرضها بالصيغ والأرقام العربية.</span>
اقترح بتعديلها هكذا:

```suggestion
  
- https://play.google.com/store/apps/details?id=com.kahraba4u.jabr
   <span dir=rtl>جبر: أول برنامج أندرويد يمكنه حل مسائل رياضيات وعرضها بالصيغ والأرقام العربية لكن للأسف ليس مفتوح المصدر.</span>
```

2024-04-24 13:53 UTC, MuhammadSawalhy commented
جميل، شكرا على هذا ال PR

2024-04-24 13:53 UTC, merged

2024-04-25 11:44 UTC, Adrhman commented
عفوًا، والشكر لكم على هذه التجميعة